# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 660a9b3d127d5d8def2517780eb3b02c3babe7a0fdd7b1ec0bd4e3218d82a4dc4dead40a66f87f0025470c0d8c1fb85572ff47806faff6ff8652b5a36fee9dd0

test:
  secret_key_base: b655fd9678510749c5a860a3ad968c0487bb2efd231c8c0fe59e7f9e689d13e7ffc391af383e61328b14907fa413e0f9f8413c007f4f5751e31de628adff8bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
